name: Select Cluster

on:
  workflow_dispatch:
    inputs:
      NAME:
        description: "Cluster Name"
        required: true
        default: "use1-1"
        type: choice
        options:
          - use1-1
          - use2-1 
          - usw2-1
env:
  CLUSTERNAME: ${{ github.event.inputs.NAME }}
  REGION: null
#    { "name": "use1-1", "region": "us-east-1" },
#    { "name": "use2-1", "region": "us-east-2" },
#    { "name": "usw2-1", "region": "us-west-2" }
#  ]
jobs:
  set-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Read cluster-name
        run: | 
          echo '${{ github.event.inputs.NAME }}'
      - name: setup region
        run: |
          case '${{ github.event.inputs.NAME }}' in 

          use1-1) 
            echo 'us-east-1' >> $REGION 
            ;;
          use2-2)
            echo 'us-east-2' >> $REGION  
            ;;
          usw2-1)
            echo 'us-west-2' >> $REGION 
            ;;
          *)
            export region=unknown
            ;;
          esac
      - name: Echo region
        run: |
          echo $REGION 
