name: Select Cluster

on:
  workflow_dispatch:
    inputs:
      NAME:
        description: "Cluster Name"
        required: true
        default: "use1-1"
        type: choice
        options:
          - use1-1
          - use2-1 
          - usw2-1
env:
  clustername: ${{ github.event.input.NAME }}
#    { "name": "use1-1", "region": "us-east-1" },
#    { "name": "use2-1", "region": "us-east-2" },
#    { "name": "usw2-1", "region": "us-west-2" }
#  ]
jobs:
  set-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Read cluster-name
        run: | 
          echo '$clustername'
      - name: setup region
        run: |
          case ${{ github.event.input.NAME }} in 

          use1-1) 
            export region=us-east-1
            ;;
          use2-2)
            export region=us-east-2 
            ;;
          usw2-1)
            export region=us-west-2
            ;;
          *)
            export region=unknown
            ;;

      - name: Echo region
        run: |
          if $region != unknown then
            echo $region
